config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get '/photos', to: 'static_pages#photos'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def photos
    render :home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flickr_helper.rb
module FlickrHelper
  def user_photos user_id, photo_count = 12
    FlickRaw.api_key = ENV['key']
    FlickRaw.shared_secret = ENV['secret']
    flickr.photos.search(user_id: user_id).first(photo_count)
  end

  def render_flickr_sidebar_widget user_id, photo_count = 12, columns = 2
    begin
      @photos = user_photos(user_id, photo_count).in_groups_of(2)
      render 'flickr/sidebar_widget'
    # rescue Exception
    #   render 'flickr/unavailable'
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/flickr/_sidebar_widget.html.erb
<div class="flickr">
  <ul>
    <% @photos.each do |row| %>
      <li>
        <% row.each do |photo| %>
          <% url = "https://farm#{photo.farm}.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}.jpg" %>
          <%= link_to(image_tag(url, title: photo.title, border: 0, :size => '75x75', class: 'flickr_photo'),
          flickr.photos.getSizes(photo_id: photo.id)[6].url ) %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/flickr/_unavailable.html.erb
<h1>Flickr unavailable</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
    <%= render_flickr_sidebar_widget(params[:flickr_id]) if params[:flickr_id]%>
    
  </body>
</html>

app/views/static_pages/home.html.erb
<%= form_tag(photos_path, method: :get) do %>
  <%= label_tag :flickr_id, 'Flickr ID:' %>
  <%= text_field_tag :flickr_id %>
  <%= submit_tag "Search Photos" %>
<% end %>